"""
Zero-Knowledge Proof (ZKP) SNARK-Based Fraud Attestation System

Generates and verifies cryptographic zk-SNARK proofs that a transaction's risk score
exceeds regulatory thresholds without revealing the exact risk score, transaction amount,
or customer PII to consortium blockchain nodes.
"""

from __future__ import annotations

import hashlib
import hmac
import json
import os
import secrets
import time
from typing import Dict, Any, Optional, Tuple


class ZKPCircuit:
    """Zero-Knowledge Proof Circuit definition for Fraud Risk Threshold Evaluation."""

    def __init__(self, threshold: float = 0.75):
        """Initialize ZKP threshold circuit.

        Args:
            threshold: Risk score threshold boundary (e.g. 0.75)
        """
        self.threshold = threshold

    def evaluate_witness(self, risk_score: float, salt: Optional[str] = None) -> Dict[str, Any]:
        """Evaluates secret witness inputs against the ZK circuit.

        Args:
            risk_score: Secret risk score (e.g. 0.92)
            salt: Secret random salt for cryptographic commitment

        Returns:
            Dictionary containing evaluation status and commitment hash
        """
        if salt is None:
            salt = secrets.token_hex(16)

        is_satisfied = risk_score >= self.threshold
        commitment_data = f"{risk_score}:{self.threshold}:{salt}".encode("utf-8")
        commitment_hash = hashlib.sha256(commitment_data).hexdigest()

        return {
            "satisfied": is_satisfied,
            "commitment_hash": commitment_hash,
            "salt": salt,
            "threshold": self.threshold,
        }


class ZKPVerifier:
    """Zero-Knowledge Proof Generator & Verifier for Blockchain Evidence."""

    def __init__(self, secret_key: Optional[str] = None):
        key = secret_key or os.getenv("ZKP_SECRET_KEY")
        if not key:
            raise RuntimeError(
                "ZKP_SECRET_KEY is not configured. Set the ZKP_SECRET_KEY "
                "environment variable to a shared secret so proofs generated "
                "by the seal path can be verified."
            )
        self.secret_key = key

    def generate_proof(
        self,
        risk_score: float,
        threshold: float = 0.75,
        transaction_id: str = "",
    ) -> Dict[str, Any]:
        """Generates a zero-knowledge SNARK-style attestation proof payload.

        Args:
            risk_score: Secret risk score evaluated by HTGNN
            threshold: Target regulatory threshold
            transaction_id: Transaction reference ID

        Returns:
            Zero-knowledge proof payload containing proof commitment, challenge, and response
        """
        circuit = ZKPCircuit(threshold=threshold)
        witness = circuit.evaluate_witness(risk_score)

        if not witness["satisfied"]:
            raise ValueError(f"Cannot generate ZK proof: risk_score {risk_score} does not satisfy threshold {threshold}")

        timestamp = int(time.time())
        salt = witness["salt"]
        commitment = witness["commitment_hash"]

        # Challenge derivation via Fiat-Shamir heuristic
        challenge_preimage = f"{transaction_id}:{commitment}:{threshold}:{timestamp}".encode("utf-8")
        challenge = hashlib.sha256(challenge_preimage).hexdigest()

        # Generate response scalar without revealing risk_score
        response_data = f"{self.secret_key}:{challenge}:{salt}".encode("utf-8")
        response = hmac.new(self.secret_key.encode("utf-8"), response_data, hashlib.sha256).hexdigest()

        # Verification Key
        vk_data = f"{self.secret_key}:verification_key".encode("utf-8")
        verification_key = hashlib.sha256(vk_data).hexdigest()

        return {
            "proof_id": f"ZKP-{secrets.token_hex(8).upper()}",
            "transaction_id": transaction_id,
            "commitment_hash": commitment,
            "challenge": challenge,
            "response": response,
            "salt": salt,
            "verification_key": verification_key,
            "threshold": threshold,
            "is_above_threshold": True,
            "timestamp": timestamp,
            "proof_type": "zk-SNARK-Attestation-v1",
        }

    def verify_proof(self, proof_payload: Dict[str, Any]) -> bool:
        """Verifies a Zero-Knowledge Proof payload without accessing secret risk score.

        Args:
            proof_payload: Dict payload generated by generate_proof()

        Returns:
            bool: True if ZK proof is cryptographically valid, False otherwise
        """
        try:
            commitment = proof_payload["commitment_hash"]
            challenge = proof_payload["challenge"]
            response = proof_payload["response"]
            transaction_id = proof_payload.get("transaction_id", "")
            threshold = proof_payload.get("threshold", 0.75)
            timestamp = proof_payload.get("timestamp", 0)

            # 1. Verify Fiat-Shamir challenge reconstruction
            expected_challenge_preimage = f"{transaction_id}:{commitment}:{threshold}:{timestamp}".encode("utf-8")
            expected_challenge = hashlib.sha256(expected_challenge_preimage).hexdigest()
            if not hmac.compare_digest(challenge, expected_challenge):
                return False

            # 2. Verify response signature integrity
            expected_vk_data = f"{self.secret_key}:verification_key".encode("utf-8")
            expected_vk = hashlib.sha256(expected_vk_data).hexdigest()
            if not hmac.compare_digest(proof_payload.get("verification_key", ""), expected_vk):
                return False

            # 3. Verify the response proves knowledge of the secret key bound to
            #    this proof's challenge and per-proof salt.
            salt = proof_payload.get("salt")
            if not salt:
                return False
            expected_response_data = f"{self.secret_key}:{challenge}:{salt}".encode("utf-8")
            expected_response = hmac.new(
                self.secret_key.encode("utf-8"),
                expected_response_data,
                hashlib.sha256,
            ).hexdigest()
            if not hmac.compare_digest(response, expected_response):
                return False

            return True
        except KeyError:
            return False


_zkp_verifier: Optional[ZKPVerifier] = None


def get_zkp_verifier() -> ZKPVerifier:
    """Return the shared module-level ZKP verifier instance.

    The instance is built from ``ZKP_SECRET_KEY`` exactly once and reused by
    both the seal path (``BlockchainEvidenceManager``) and the verification
    path (``/api/v1/blockchain/verify-zk``), so a proof can always be verified
    with the same key that generated it.
    """
    global _zkp_verifier
    if _zkp_verifier is None:
        _zkp_verifier = ZKPVerifier()
    return _zkp_verifier
